PLFC-139 - vtx-react-scripts (internal runner for vtx-create-react)
vertexinc/vtx-ui-react-scripts pull request #8
Opened 2021-03-04 18:13 UTC by dartamonov-vertex

2021-03-05 13:43 UTC, mellis481 commented
@dartamonov-vertex I pushed a commit that updates the lerna config so that lerna does not track the template "package", but rather only `vtx-react-scripts` and `vtx-create-react`.  I also ran `lerna bootstrap`.

2021-03-08 21:30 UTC, dgreene1 requested changes
Gave a first pass of comments. I'll review more tomorrow. Next time, we should get the code in front of me sooner. It's hard to review a 57,037 line PR.

2021-03-08 21:30 UTC, dgreene1 commented on packages/vtx-create-react/.eslintignore
> +/microfrontend-template
Is there a reason why we'd want to do this? Wouldn't we want to know if our template is gross?

2021-03-08 21:30 UTC, dgreene1 commented on packages/vtx-create-react/lib/index.js
>  const cli_ux_1 = tslib_1.__importDefault(require("cli-ux"));
This appears to be a  post-transpilation file. That tells me that we shouldn't be checking this in at all. Shouldn't we have *.js in our .gitignore?

2021-03-08 21:30 UTC, dgreene1 commented on packages/vtx-create-react/lib/index.js.map
> -{"version":3,"file":"index.js","sourceRoot":"","sources":["../src/index.ts"],"names":[],"mappings":";;;;AAAA,4CAAgD;AAChD,4DAAyB;AACzB,6EAAyE;AACzE,iFAAwH;AAExH,MAAM,WAAW,GAAG,YAAY,CAAC;AACjC,MAAM,mB
shouldn't *.js.map be in our .gitignore file? Maybe just ignore the whole /lib folder right?

2021-03-08 21:30 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/build.ts
> +    load(() => {
What is `load` doing?

2021-03-08 21:30 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/build.ts
> +            console.log(err);
You need to throw errors because otherwise people's builds won't fail in CICD. You can't have a failing webpack run but a green Jenkins run (or a green Github Actions workflow either).

2021-03-08 23:54 UTC, dgreene1 requested changes
2nd review. Please check the first review questions too.

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/cypress-run.ts
> +      cypress.run({
@mellis481 / @dartamonov-vertex I’m wondering now if we’d be shooting ourselves in the foot by trying to wrap the native cypress run commands. I think the scaffolding for Cypress is valuable, but we might be creating a maintenance headache by not letting people choose which browsers and which runtime flags they can send, etc. Our wrapping CLI approach has a lot  of appeal for build, test, start, lint, etc. I’m only having cold feet about being a blocker to Cypress modifications.

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/lint.ts
> +        console.error('error', error);
Is this the right order of commenting and error code? Also why should we catch it at all? A failure should propagate out and kill the process.

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/lint.ts
> +        const results = await eslint.lintFiles([path.resolve(process.cwd(), 'src/*')]);
Do they have a synchronous version? I’m nervous these async methods will return after the process returns successfully (like in a fire and forget manner).

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/build.ts
> +          projectPath: process.cwd(),
@dartamonov-vertex / @mellis481 I believe we talked about pulling in the team’s tsconfig. I don’t see that happening here. Where are we doing that?

(sorry for not finding it myself but this PR is huge and my time is limited)

Update: I found it. It’s in one of the CLIs but not both start and build. Gotta DRY that up.

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/webpack.config.ts
> +        // by default project's tsconfig.json is used, to pass different config - tsconfig: path.resolve(__dirname, '../tsconfig.mfe.json'),
If we’re going to use the default we must verify that the file exists first and if not, throw an error.

Also, commented out code is dead code and dead code should be removed.

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/webpack.config.ts
> +        CALC_CONFIG_MFE_PATH: JSON.stringify(envConfig.CALC_CONFIG_MFE_PATH),
@mellis481 / @bradtulig-vertex / @dartamonov-vertex is this PR really ready for review when there is stuff like this in there that is clearly copy and paste that should not have been brought over, you know?

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/test.ts
> +          console.error(failure);
Again, the process must be a failing process ID. So it is counterproductive and would create a false positive to swallow an error. Instead don’t try catch at all and don’t .catch

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/start.ts
> +      server.listen(port, 'localhost', function (err: Error | undefined) {
@mellis481 / @dartamonov-vertex can one of you test that when you kill the process by doing “control + c” that it kills the webpack run?

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/start.ts
> +      server.listen(port, 'localhost', function (err: Error | undefined) {
You should never have to override the parameters of a function unless it’s of type any. @mellis481 this would be one of those things for your typescript doc since everyone does it and it’s so a real anti pattern.

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/commands/cypress-run-e2e.ts
> +      cypress.open({
It says .open here. Did you mean .run?

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-create-react/package.json
> +  "gitHead": "22b054b32fb119d3ecb4d5e62f4760dc061f9a60"
What’s this?

2021-03-08 23:54 UTC, dgreene1 commented on packages/vtx-react-scripts/src/webpack.config.ts
> +      new ForkTsCheckerWebpackPlugin({
We need to confirm (and ideally with a unit test) that ForkTsChecker fails a build when there’s a TS error. I know it sends them to the console, but does it return a bad exit code as expected when building?

2021-03-09 00:46 UTC, mellis481 commented on packages/vtx-create-react/.eslintignore
> +/microfrontend-template
That would require us to install all dependencies that the template needs in vtx-create-react.

2021-03-09 00:47 UTC, mellis481 commented on packages/vtx-create-react/lib/index.js
>  const cli_ux_1 = tslib_1.__importDefault(require("cli-ux"));
At one point I was gitignoring /lib, but I think I removed that during testing.

2021-03-09 00:48 UTC, mellis481 commented on packages/vtx-react-scripts/src/commands/cypress-run.ts
> +      cypress.run({
If there are a handful of flags we'd want to pass through that wouldn't be too hard.

2021-03-09 01:03 UTC, mellis481 commented on packages/vtx-create-react/package.json
> +  "gitHead": "22b054b32fb119d3ecb4d5e62f4760dc061f9a60"
`gitHead`? Not sure. We noticed it today. Appears to be part of lerna publish.  We will determine what it is shortly.

2021-03-09 13:28 UTC, mellis481 commented on packages/vtx-create-react/package.json
> +  "gitHead": "22b054b32fb119d3ecb4d5e62f4760dc061f9a60"
Looks like this is due to the me naming a script in the root package.json which calls `lerna publish`, `publish`. I renamed it to `release`. https://github.com/lerna/lerna/issues/1880

2021-03-09 17:51 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/build.ts
> +    load(() => {
Looks like it left from the time we thought that we would be calling npm commands from these scripts. Removed.

2021-03-09 17:51 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/build.ts
> +            console.log(err);
Updated

2021-03-09 17:52 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/build.ts
> +          projectPath: process.cwd(),
We are not passing it anymore. Going with project's tsconfig pulled by default in ForkTsCheckerWebpackPlugin

2021-03-09 17:53 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/webpack.config.ts
> +        // by default project's tsconfig.json is used, to pass different config - tsconfig: path.resolve(__dirname, '../tsconfig.mfe.json'),
Removed

2021-03-09 17:54 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/start.ts
> +      server.listen(port, 'localhost', function (err: Error | undefined) {
It does

2021-03-09 17:55 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/start.ts
> +      server.listen(port, 'localhost', function (err: Error | undefined) {
Updated

2021-03-09 17:55 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/cypress-run-e2e.ts
> +      cypress.open({
Renamed files

2021-03-09 18:23 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/webpack.config.ts
> +      new ForkTsCheckerWebpackPlugin({
Example
![image](https://user-images.githubusercontent.com/41914249/110518844-a1c1f180-80da-11eb-9d2d-4e78d30afeaf.png)

2021-03-09 18:31 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/test.ts
> +          console.error(failure);
Removed

2021-03-09 18:44 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/lint.ts
> +        console.error('error', error);
Removed

2021-03-09 18:48 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/lint.ts
> +        const results = await eslint.lintFiles([path.resolve(process.cwd(), 'src/*')]);
I didn't see a way to do it synchronously based on their documentation - https://eslint.org/docs/developer-guide/nodejs-api#-eslintlintfilespatterns

2021-03-11 18:25 UTC, dartamonov-vertex commented on packages/vtx-react-scripts/src/commands/lint.ts
> +        const results = await eslint.lintFiles([path.resolve(process.cwd(), 'src/*')]);
Updated

2021-03-12 13:36 UTC, mellis481 approved these changes

2021-03-12 13:36 UTC, merged